let level1;

function startLevel() {
    level1 = new Level(

        [
            new Chicken('img/3_enemies_chicken/chicken_normal/1_walk/1_w.png'),
            new Chicken('img/3_enemies_chicken/chicken_normal/1_walk/1_w.png'),
            new Chicken('img/3_enemies_chicken/chicken_normal/1_walk/1_w.png'),
        ], [
            new Cloud(100),
            new Cloud(200),
            new Cloud(250),
            new Cloud(290),
            new Cloud(330),
            new Cloud(370),
            new Cloud(410),
            new Cloud(450),
            new Cloud(490),
            new Cloud(530),
            new Cloud(570),
            new Cloud(610),
            new Cloud(650),
            new Cloud(690),
            new Cloud(730),
            new Cloud(770),
            new Cloud(810),
            new Cloud(850),
            new Cloud(890),
            new Cloud(930),
            new Cloud(970),
            new Cloud(1010),
            new Cloud(1050),
            new Cloud(1090),
            new Cloud(1130),
            new Cloud(1170),
            new Cloud(1210),
            new Cloud(1250),
            new Cloud(1290),
            new Cloud(1330),
            new Cloud(1370),
            new Cloud(1410),
            new Cloud(1450),
            new Cloud(1490),
            new Cloud(1530),
            new Cloud(1570),
            new Cloud(1610),
            new Cloud(1650),
            new Cloud(1690),
            new Cloud(1730),
            new Cloud(1770),
            new Cloud(1810),
            new Cloud(1850),
            new Cloud(1890),
            new Cloud(1930),
            new Cloud(1970)
        ], [
            new backgroundObjekt('img/5_background/layers/air.png', -719 * 2, ),
            new backgroundObjekt('img/5_background/layers/3_third_layer/1.png', -719 * 2, ),
            new backgroundObjekt('img/5_background/layers/2_second_layer/1.png', -719 * 2, ),
            new backgroundObjekt('img/5_background/layers/1_first_layer/1.png', -719 * 2, ),
            new backgroundObjekt('img/5_background/layers/air.png', -719, ),
            new backgroundObjekt('img/5_background/layers/3_third_layer/2.png', -719, ),
            new backgroundObjekt('img/5_background/layers/2_second_layer/2.png', -719, ),
            new backgroundObjekt('img/5_background/layers/1_first_layer/2.png', -719, ),

            new backgroundObjekt('img/5_background/layers/air.png', 0, ),
            new backgroundObjekt('img/5_background/layers/3_third_layer/1.png', 0, ),
            new backgroundObjekt('img/5_background/layers/2_second_layer/1.png', 0, ),
            new backgroundObjekt('img/5_background/layers/1_first_layer/1.png', 0, ),
            new backgroundObjekt('img/5_background/layers/air.png', 719, ),
            new backgroundObjekt('img/5_background/layers/3_third_layer/2.png', 719, ),
            new backgroundObjekt('img/5_background/layers/2_second_layer/2.png', 719, ),
            new backgroundObjekt('img/5_background/layers/1_first_layer/2.png', 719, ),

            new backgroundObjekt('img/5_background/layers/air.png', 719 * 2, ),
            new backgroundObjekt('img/5_background/layers/3_third_layer/1.png', 719 * 2, ),
            new backgroundObjekt('img/5_background/layers/2_second_layer/1.png', 719 * 2, ),
            new backgroundObjekt('img/5_background/layers/1_first_layer/1.png', 719 * 2, ),
            new backgroundObjekt('img/5_background/layers/air.png', 719 * 3, ),
            new backgroundObjekt('img/5_background/layers/3_third_layer/2.png', 719 * 3, ),
            new backgroundObjekt('img/5_background/layers/2_second_layer/2.png', 719 * 3, ),
            new backgroundObjekt('img/5_background/layers/1_first_layer/2.png', 719 * 3, ),
        ], [
            new SalsaBottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 50),
            new SalsaBottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 400),
            new SalsaBottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 200),
            new SalsaBottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 250),
            new SalsaBottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 450),
            new SalsaBottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 650),
            new SalsaBottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 700),
            new SalsaBottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 750),
            new SalsaBottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 1000),
            new SalsaBottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 1200),
            new SalsaBottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 1500),
            new SalsaBottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 1700),
        ], [
            new Coin('img/8_coin/coin_1.png', 150),
            new Coin('img/8_coin/coin_1.png', 300),
            new Coin('img/8_coin/coin_1.png', 250),
            new Coin('img/8_coin/coin_1.png', 550),
            new Coin('img/8_coin/coin_1.png', 700),
            new Coin('img/8_coin/coin_1.png', 750),
            new Coin('img/8_coin/coin_1.png', 1000),
            new Coin('img/8_coin/coin_1.png', 1200),
            new Coin('img/8_coin/coin_1.png', 1500),
            new Coin('img/8_coin/coin_1.png', 1700),
        ], [
            new Endboss('img/4_enemie_boss_chicken/1_walk/G1.png'),
        ], [
            new HealthItem('img/objekte/mexico-g1b46101a5_1280.png', 50),
            new HealthItem('img/objekte/mexico-g1b46101a5_1280.png', 250),
            new HealthItem('img/objekte/mexico-g1b46101a5_1280.png', 450),
            new HealthItem('img/objekte/mexico-g1b46101a5_1280.png', 500),
            new HealthItem('img/objekte/mexico-g1b46101a5_1280.png', 800),
        ], [
            new JumpChicken('img/3_enemies_chicken/chicken_normal/1_walk/1_w.png', 1000),
            new JumpChicken('img/3_enemies_chicken/chicken_normal/1_walk/1_w.png', 700),
            new JumpChicken('img/3_enemies_chicken/chicken_normal/1_walk/1_w.png', 400),
        ], [
            new InfiniteChicken('img/3_enemies_chicken/chicken_normal/1_walk/1_w.png', 250),
            new InfiniteChicken('img/3_enemies_chicken/chicken_normal/1_walk/1_w.png', 750),
        ], [
            new MidCloud(60),
            new MidCloud(230),
            new MidCloud(460),
            new MidCloud(790),
            new MidCloud(1020),
            new MidCloud(1250),
            new MidCloud(1480),
            new MidCloud(1710),
            new MidCloud(1940),
            new MidCloud(2170),
            new MidCloud(2400),
            new MidCloud(2630),
            new MidCloud(2860),
            new MidCloud(3090)
        ], [
            new HighCloud(0),
            new HighCloud(150),
            new HighCloud(300),
            new HighCloud(450),
            new HighCloud(600),
            new HighCloud(750),
            new HighCloud(900),
            new HighCloud(1050),
            new HighCloud(1200),
            new HighCloud(1350),
            new HighCloud(1500),
            new HighCloud(1650),
        ],
    );
}